export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGFAILED = 'FETCH_INGFAILED';

export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAILED = 'PURCHASE_FAILED';
export const PURCHASE_START = 'PURCHASE_START';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const ORDERS_START = 'ORDERS_START';
export const ORDERS_SUCCESS = 'ORDERS_SUCCESS';
export const ORDERS_FAILED = 'ORDERS_FAILED';
//export const ORDERS_INIT = 'ORDERS_INIT';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT';